### PR TITLE
feat: add warning when skipping wifi page

### PR DESCRIPTION
**Pull request by olivierwilkinson**
Sorry for the extra lines in here, I was auto-formatting and it's made the diff pretty gnarly

### CODE REVIEW

**Comment by jcapona** [comment]
nice! works for me... I think it'd be great if we could either reduce the height of the dialog or increase the line spacing so we don't get this large white space between the text and the buttons.

image

**Comment by olivierwilkinson** [comment]
> nice! works for me... I think it'd be great if we could either reduce the height of the dialog or increase the line spacing so we don't get this large white space between the text and the buttons.

I agree the whitespace is a bit big isn't it? I was working from [these designs from inga](https://pi-top.atlassian.net/jira/software/c/projects/SWE/boards/173?modal=detail&selectedIssue=OS-1157&assignee=5cb3f932ff4c750e404c62a4). In them the buttons are actually a bit higher so it doesn't look as bad; I can move the dialog buttons to match the designs if you prefer the look of that? Ideally we should keep the height of our dialogs consistent because it means the dialog buttons always appear in the same place.

**Comment by jcapona** [comment]
ah true! okay, if that's the case we can work the button size/styles when we get to [this ticket](https://pi-top.atlassian.net/browse/OS-1146)... I think we can merge this then!

**Review by jcapona — APPROVED** [review]

**Comment by olivierwilkinson** [comment]
> ah true! okay, if that's the case we can work the button size/style when we get to [this ticket](https://pi-top.atlassian.net/browse/OS-1146)... I think we can merge this then!

Nice! I'll go to that ticket and add a comment so we don't forget :)

**Pull request merged**
