### PR TITLE
Os 1388 fix onboarding on android mobiles

### PR DESCRIPTION
**Pull request by olivierwilkinson**
| Status  | Ticket/Issue |
| :---: | :--: |
| Ready | [OS-1388](https://pi-top.atlassian.net/browse/OS-1388) |

### CODE REVIEW

**Comment by jcapona** [comment]
The buttons are now indeed visible, but sometimes when they're around the build information area at the bottom right, they can't be clicked. 

For example, in the following picture, the left-side of the button is clicked but the right side isn't. Also, the skip button can't be clicked.

image

**Comment by olivierwilkinson** [comment]
> The buttons are now indeed visible, but sometimes when they're around the build information area at the bottom right, they can't be clicked.
> 
> For example, in the following picture, the left-side of the button is clicked but the right side isn't. Also, the skip button can't be clicked.
> 
> image

Ah interesting, I'll see if I can make it so it's visible on landscape but not portrait, that will still be good enough for support purposes. I'll also put the build info in the background so that they don't intercept click events even if they overlap on some screens.

**Comment by olivierwilkinson** [comment]
@jcapona I've fixed the issue with the build info now if you want to give it another go 😄

**Comment by jcapona** [comment]
Nice, works great now. The build info is still visible but the buttons can be clicked.

However, since you talked about landscape mode, I checked using my phone and sometimes the buttons go out of view.

image

Not sure if that's in the scope of this ticket though

**Comment by olivierwilkinson** [comment]
> However, since you talked about landscape mode, I checked using my phone and sometimes the buttons go out of view.

Yeah I noticed that too, I decided to leave it for now since users can go back to portrait mode to continue if they want. It's also not easy to fix without doing some design work, for example the inputs should also be visible otherwise it is not clear why they are unable to continue in some cases.

**Comment by olivierwilkinson** [comment]
> It's also not easy to fix without doing some design work, for example the inputs should also be visible otherwise it is not clear why they are unable to continue in some cases.

Actually I may have an easy fix that improves most cases, just a sec.

**Comment by olivierwilkinson** [comment]
@jcapona ok I've added a couple quick improvements for mobile landscape, there are a few cases relating to error messages being shown where it's still not perfect but otherwise it will work in mobile landscape now :)

**Review by jcapona — APPROVED** [review]
nice, works great now!

**Pull request merged**
