### PR TITLE
Don't hang when stopping systemd service 

### PR DESCRIPTION
**Pull request by jcapona**
Ticket: https://pi-top.atlassian.net/browse/OS-1192

Reboot after the onboarding finishes may take a few minutes, which causes a 'no SD card' animation to appear in the miniscreen of a pi-top [4]. 

After the initial approach made in https://github.com/pi-top/pi-topOS-Web-Portal/pull/317 and investigating the actual cause of the issue, I found that the web-portal service isn't stopping properly when `systemd` requests it (in this case, when the system reboots). This causes the system to hang for ~90 seconds waiting for the service to finish until it timeouts:

```
Jan 17 00:40:00 pi-top systemd[1]: Stopping pi-topOS Web Server...
Jan 17 00:40:00 pi-top pt-os-web-portal[461]: Stopping...
Jan 17 00:40:00 pi-top pt-os-web-portal[461]: Stopped: OS updater
Jan 17 00:40:00 pi-top pt-os-web-portal[461]: Stopped: Connection manager
Jan 17 00:40:00 pi-top pt-os-web-portal[461]: Stopped: WSGI Server
Jan 17 00:41:30 pi-top systemd[1]: pt-os-web-portal.service: State 'stop-sigterm' timed out. Killing.
Jan 17 00:41:30 pi-top systemd[1]: pt-os-web-portal.service: Killing process 461 (pt-os-web-porta) with signal SIGKILL.
Jan 17 00:41:30 pi-top systemd[1]: pt-os-web-portal.service: Killing process 926 (pt-os-web-porta) with signal SIGKILL.
Jan 17 00:41:30 pi-top systemd[1]: pt-os-web-portal.service: Killing process 927 (pt-os-web-porta) with signal SIGKILL.
Jan 17 00:41:30 pi-top systemd[1]: pt-os-web-portal.service: Killing process 1299 (n/a) with signal SIGKILL.
Jan 17 00:41:30 pi-top systemd[1]: pt-os-web-portal.service: Main process exited, code=killed, status=9/KILL
Jan 17 00:41:30 pi-top systemd[1]: pt-os-web-portal.service: Failed with result 'timeout'.
Jan 17 00:41:30 pi-top systemd[1]: Stopped pi-topOS Web Server.
```

The approach taken here is to force the application to exit using `exit()` after cleanup is completed (i.e.: the `stop()` method finishes).

### CODE REVIEW

**Comment by olivierwilkinson** [comment]
The reboot is definitely much quicker. The device was up again before the warning text showed up on the onboarding page, only by about 5 seconds though (we may want to increase that timeout significantly).

I did still have the no memory card warning and the device powered itself down again. I'll try again from scratch now.

**Comment by olivierwilkinson** [comment]
> The reboot is definitely much quicker. The device was up again before the warning text showed up on the onboarding page, only by about 5 seconds though (we may want to increase that timeout significantly).
> 
> I did still have the no memory card warning and the device powered itself down again. I'll try again from scratch now.

This time I did get through it without the warning coming up at all, and didn't receive the 'no SD card' animation. I'm going to do it one last time to be sure because I triggered the reboot when on the wrong network and only noticed after a few things had failed.

**Comment by olivierwilkinson** [comment]
I tried it again just now, the reboot finished after about 1m30s but I got the 'no SD card' animation and it powered down. After turning it back on it did connect to the right wifi network and took the browser to the landing page. In total it was about 2m and the warning showed.

It could be that I'm not installing this package correctly so maybe let's go through it together soon.

**Comment by olivierwilkinson** [comment]
I had another run through this morning with the newest nightly build. I think there is an unrelated issue to do with my network that is causing the pi-top network to come down while I'm trying to connect to my wifi. It does successfully connect to the wifi network however, and more importantly it reboots quickly and the 'no SD card' animation doesn't show up at all.

I recorded my screen throughout so here is a video which shows the wifi issues I found. I inspected the network tab since I had found issues when connecting to wifi before:

https://user-images.githubusercontent.com/15321261/150334769-ff5b35dd-e50a-4586-92c6-a6ddb610000a.mov

**Comment by zz-james** [comment]
I downloaded and installed the .deb files onto my pi-top and rebooted and it was pretty quick. I'm not sure it you need me to go through the whole onboarding flow? in which case maybe a n00b question but do I have to burn the sd-card again and what image to use?

**Comment by olivierwilkinson** [comment]
> I downloaded and installed the .deb files onto my pi-top and rebooted and it was pretty quick. I'm not sure it you need me to go through the whole onboarding flow? in which case maybe a n00b question but do I have to burn the sd-card again and what image to use?

Yeah I think the problem is mainly after the initial reboot during onboarding. Here are the instructions @jcapona gave me for setting up the OS so you can install this deb before going through the onboarding:

- burn an OS image into a SD card
- download the web-portal .deb files into your laptop

Screenshot 2022-01-20 at 15 01 18

- before removing the SD card from your laptop, enable ssh by running `touch /Volumes/boot/ssh`  (assuming you’re using a macbook)
- unzip the archive downloaded above and copy the debs into the SD card: `cp *.deb /Volumes/recovery`  (assuming you’re using a macbook)
-  put the SD card into the pi-top and boot it up… wait until the onboarding is ready
- once it boots, ssh into it through the USB cable or AP (use IP 192.168.90.1 if using AP network)
- install the .debs by running `sudo apt install /boot/.recovery/*.debs`
- reboot the pi-top so that you get the new web-portal ; `sudo reboot` or just force it using the power switch

**Pull request merged**
