### PR TITLE
Onboarding minscreen copy changes

### PR DESCRIPTION
**Pull request by angusjfw**
- miniscreen arrows is merged here
- various small copy tweaks
- skip the 2nd page 'Thats it'
- move detailed instructions page to after laptop page
- remove 'lets get started' from the laptop page
- skip ahead when connection detected from wifi info page too
- allow pressing down on waiting for connection page
- Fix no down arrow on browser page when final page is visible

### CODE REVIEW

**Comment by angusjfw** [comment]
build hasn't retriggered but there is a deb build of the latest commit on the branch (3095300) here
https://github.com/pi-top/pi-topOS-Web-Portal/actions/runs/1795729762

**Review by olivierwilkinson — CHANGES_REQUESTED** [review]
There is a missing apostrophe at the beginning of the password, although the apostrophes could be removed imo. I also thought we were going to add `pass:` before it? Is there a reason that wasn't possible?
IMG_6638 2

The 'Detailed setup instructions'  page still feels like an instruction, I can see lots of people heading to that URL at that point. Maybe "If you get stuck, go here:" is better, since it's saying that it is only if they need it. Alternatively: "If needed, detailed instructions here" or something. Also, I'd be interested to hear what everyone thinks about the placement of this page. I think the idea of moving it after the 'You will need a computer' page is actually worse, particularly if we do change to copy to be clearer.

My other points are minor, feel free to ignore:

Pressing up on the first page is also still moving us down to the next page, this is a little weird considering we are specifying down now. I'm ok with removing this later, or even leaving it since it's not very discoverable.

I know we've agreed to keep the "Awesome! Press DOWN to continue" page but still I feel like it's redundant since it says essentially the same thing as the previous page. The arrows really help indicate that you can press the buttons so it doesn't seem necessary to me.

**Comment by angusjfw** [comment]
> There is a missing apostrophe...

Don't know why that is missing. I've added 'pass:' now so hopefully that will fix it...

> I know we've agreed to keep the "Awesome! Press DOWN to continue" page but still I feel like it's redundant...

yeah...it is, i've removed it

> The 'Detailed setup instructions' page still feels like an instruction..

I've changed the text to 'Need more guidance:' to make fell more optional. I think moving it before laptop page will make it feel more required and break up the flow, better to start with an easy instruction so they continue pressing down and that... particularly after we removed the 'press down again' thing

**Comment by zz-james** [comment]
this is working ok for me. I think these are good changes, reads well, fits on screen nicely

**Review by zz-james — APPROVED** [review]

**Pull request merged**
